### PR TITLE
Use skimage.filters and alias scipy.ndimage as ndi not nd

### PR DESCRIPTION
**Pull request by JDWarner**
This avoids a warning which was otherwise thrown because of `skimage.filter` being imported then aliased to `filters`. Now we just import `filters`.

Also, I strongly prefer the convention of `import skimage.ndimage as ndi` to better differentiate from the usual NumPy `np` namespace.

### CODE REVIEW

**Comment by jni** [comment]
Big :-1: on `ndi`. I see the `nd` alias much more frequently, and I prefer 2-char aliases in general (eg. pandas as pd, toolz as tz).

At least, this should be a major discussion with @scikit-image/core. The library internals should be consistent with what we advocate. Currently, we have 10 `as nd` imports vs 5 `as ndi`.

**Comment by blink1073** [comment]
I read nd as n-dims. In this case I prefer (and use) ndi.



—

**Comment by JDWarner** [comment]
I'm fairly certain I started using the `ndi` alias because that is how the examples in `scipy.ndimage` docstrings were formatted. They have all been since revised to use no alias at all, just `from scipy import ndimage`. I prefer it for three reasons:

1. `np` and `nd` are not well visually differentiated. With the modern propensity for thin fonts, they differ by a couple of pixels. When reading quickly or when calls are mixed in a single line, this can be an issue. Adding a third character makes them very distinct. 
2. Subjectively, I find `ndi` maps directly to `scipy.ndimage` in my mind while `nd` has multiple possible meanings/connotations, as Steven points out.

The obvious downside is that it comes at the cost of a third character. I find I only reach for `scipy.ndimage` for occasional calls on the order of 1-3 lines per file, so I personally view `ndi` as worth the cost.

If it required a shift modifier, I'd change my tune ;)

**Comment by jni** [comment]
I'm slowly coming around... @stefanv @emmanuelle @ahojnnes opinions?

**Comment by stefanv** [comment]
I've always used ``ndi``--not sure when ``nd`` creeped into scikit-image.

**Comment by ahojnnes** [comment]
I am fine with either... also happy with `from scipy import ndimage`.

**Comment by jni** [comment]
@stefanv not sure about "creeped" but it probably crept in there when I added it. =P

Ok, given historical usage and support leaning much more in favour of `ndi`, let's unify around that. I'll submit a PR replacing `nd` inside the library shortly.

**Comment by jni** [comment]
Looks like this can go in now. =) Thanks @JDWarner!

**Pull request merged**
