### PR TITLE
Update panorama stitching for 0.12, where bg vals are 0 by default

### PR DESCRIPTION
**Pull request by stefanv**
/cc @JDWarner

### CODE REVIEW

**Comment by JDWarner** [comment]
This works, but I believe you can also just add one to all of the previous expected labels rather than setting the background to a non-default value.

Thinking big picture, we probably should refactor the flood-fill out of `label` and expose it directly. Using flood fill here would likely be clearer to students and useful for our users. I can take this on if you like. Too bad I forgot to do that before 0.12 was out the door.

**Comment by jni** [comment]
I would use a 3D flood fill as soon as it was on master... =)

**Comment by JDWarner** [comment]
Looking at this, I'm not sure `label` uses a canonical flood fill.

**Comment by stefanv** [comment]
Yes, please go ahead, Josh. I will be updating the tutorial content soon,
so this would be super helpful.

**Pull request closed without merging**
