### PR TITLE
First steps: convert repo to Jupyter Book

### PR DESCRIPTION
**Pull request by jni**
Hi everyone,

I've started to convert our jupyter notebooks to the Jupyter Book format. I'm pretty excited to report that it's going really well! 

Screen Shot 2020-08-01 at 12 04 08 am

There's still a few steps to figure out but my suggested course of action is:

- fix up the index
- convert notebooks to jupytext format
- clean up the currently notebooks (numpy, filters, morphology, segmentation, 3D), e.g. make sure each heading is the appropriate level (we jump around curretnly), try to minimise dependence of later cells on earlier exercises, etc.
- merge this PR
- slowly port the rest of the notebooks into the book (currently they are siloed)

@stefanv I mistakenly thought I had to nuke your earlier pure-sphinx book effort. However I think that content was pretty out of date (they were "frozen" copies of existing notebooks in an old state), so I think that's ok. Let me know if you want me to restore some/all of that content and I will, now that I know that I can ignore entire folders.

@JDWarner I've totally come around to your style of teaching segmentation (default parameters are often nonsense, play around to find a good parameter set), but it doesn't make for good reading in book format. With your permission I'd like to adapt the lesson to be more readable. Let me know if you'd like to participate in that effort!

### CODE REVIEW

**Comment by alexdesiqueira** [comment]
Great stuff Juan! Thank you!

**Comment by jni** [comment]
@scikit-image/core this is working now! Thanks to @GenevieveBuckley who figured out jupyter/nbclient#97, the 3D notebook now renders as a jupyterbook, with napari screenshots embedded:

Screen Shot 2020-11-27 at 1 01 30 am

Screen Shot 2020-11-27 at 1 01 03 am

It's pretty sweet! At this point I would like to merge this then keep working on moving from ipynb format to jupytext format, then progressively converting all existing lessons.

**Review by mkcor — APPROVED** [review]
Exciting!

**Comment by stefanv** [comment]
Excited to see the tutorials move in this direction. Thanks, Juan!

Maybe we can also provide instructions to contributors on how to setup a system where they can edit notebooks and have those saved as Markdown for contributing back. 

/cc @rossbar who is working on something similar for NumPy

**Comment by jni** [comment]
Yes the plan is to have the notebooks saved in a jupytext format.

**Pull request merged**
