### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by jni**
The repo did not have an associated license. This rectifies the situation and ensures people can use these materials in their work.

### CODE REVIEW

**Comment by stefanv** [comment]
Why not just license the code CC0 too?

**Comment by jni** [comment]
@stefanv Why not license skimage itself as CC0? I dunno. BSD just seems more appropriate to code.

**Comment by stefanv** [comment]
I think tutorials are very different from library code.  We want to maximally encourage copy, paste, modification of this code here.  We don't want people to have to worry about inadvertently breaking copyright conditions while playing with the tutorial, and perhaps adapting it for play or work.

**Comment by jni** [comment]
@stefanv fair point, addressed.

**Pull request merged**
